# fly.toml file generated for broken-darkness-9502 on 2023-04-12T13:08:49-07:00

app = "broken-darkness-9502"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sea"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
