### Valid

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Justy Ober",
    "number": "555-55555"
}

### Missing Name

POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "555-555-5555"
}

### Missing number

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "Justy Oberg"
}

### Name exists

POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}

### 

PUT http://localhost:3001/api/persons/64370276dd8467baf83fd6e3
content-type: application/json

{
    "name": "arto hellas",
    "number": "04r4246"
}